In [2]:
import torch
print(torch.__version__)

1.7.0+cpu


In [3]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array 

tensor([[1., 2.],
        [4., 5.]])

In [8]:
tensor_uninitialized = torch.Tensor(3,3)
tensor_uninitialized
torch.numel(tensor_uninitialized)

9

In [9]:
tensor_rand = torch.rand(2,3)
tensor_rand

tensor([[0.3968, 0.0163, 0.8805],
        [0.6713, 0.2426, 0.0611]])

In [10]:
tensor_long = torch.LongTensor([1.0,2.0,3.0])
tensor_long

<ipython-input-10-809280c6b4d9>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_long = torch.LongTensor([1.0,2.0,3.0])


tensor([1, 2, 3])

In [11]:
tensor_byte = torch.ByteTensor([0,261,1,-5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [12]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
tensor_zeros = torch.zeros(10)
tensor_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [16]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)
tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
initial_tensor = torch.rand(3,3)
initial_tensor.fill_(3)
#inplace operation ends with _

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [21]:
new_tensor = initial_tensor.add(4) #initial tensor stays unchanged
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [22]:
initial_tensor

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [23]:
import numpy as np

numpy_arr = np.array([1,2,3])
numpy_arr

array([1, 2, 3])

In [24]:
#create pytorch tensor from numpy array
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [26]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [27]:
tensor
#tensors created from numpy array share same memory 

tensor([1, 4, 3], dtype=torch.int32)

In [28]:
initial_tensor = torch.rand(2,3)
initial_tensor[0,2]

tensor(0.0712)

In [29]:
initial_tensor[:,1:]


tensor([[0.9276, 0.0712],
        [0.9090, 0.6889]])

In [30]:
initial_tensor.size()

torch.Size([2, 3])

In [32]:
initial_tensor.shape

torch.Size([2, 3])

In [33]:
resized_tensor = initial_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [34]:
resized_tensor

tensor([0.2340, 0.9276, 0.0712, 0.8120, 0.9090, 0.6889])

In [35]:
initial_tensor[0,2] = 0.1111
resized_tensor

tensor([0.2340, 0.9276, 0.1111, 0.8120, 0.9090, 0.6889])

In [36]:
resized_tensor = initial_tensor.view(3,2)
resized_tensor.shape

torch.Size([3, 2])

In [37]:
#-1 indicates that that dimension remains untouched
resized_matrix = initial_tensor.view(-1,2)
resized_matrix.shape

torch.Size([3, 2])

In [41]:
sorted_tensor , sorted_indices = torch.sort(initial_tensor)
sorted_tensor

tensor([[0.1111, 0.2340, 0.9276],
        [0.6889, 0.8120, 0.9090]])

In [44]:
sorted_indices

tensor([[2, 0, 1],
        [2, 0, 1]])

In [45]:
sorted_tensor,sorted_indices = torch.sort(initial_tensor,dim=0)
#dim = 0 : sort only columns
sorted_tensor

tensor([[0.2340, 0.9090, 0.1111],
        [0.8120, 0.9276, 0.6889]])

In [46]:
# Computational graph example:

from torch.autograd import Variable

# Wh =>  h =>    Wx =>   x
x = Variable(torch.randn(1,10))
h =  Variable(torch.randn(1,20))
W_h = Variable(torch.randn(20,20))
W_x = Variable(torch.randn(20,10))

# torch.mm multiply matrices
#t transpose
h_prod = torch.mm(W_h,h.t())
x_prod =  torch.mm(W_x,x.t())

next_h = (h_prod + x_prod).tanh()
loss = next_h.sum()
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn